### ISSUE TITLE
Login is not working 

### ISSUE THREAD

**Issue by jjakshay** [ricohapi/video-streaming-sample-app#3]
I am trying the sample application on my localhost. But somehow I am not able to login into the webpage. 
Each time app is saying login failed. 

Can you please confirm , which login id I have use for login into app. 

I can successfully login with my id here https://entry.contest.theta360.com/
Also i have tried to login with my credentials which I created on https://beta2.ucs.ricoh.com/dashboard/login?lang=en

Please let me know, How I can get sample app working.

Thanks,
Akshay

**Comment by aikw** [comment]
I found a bug on password handling.
It has been fixed by #4.
Could you please try the latest code?

**Comment by codetricity** [comment]
I have tried the new sample code. Like @jjakshay, I can't login. My username and password do not have a + sign. Is it possible to get a demo credentials for the username and password that are known to work? I can use my login and credentials with the other sample app.

**Comment by aikw** [comment]
@jjakshay, I found  codetricity's good guide.
http://theta360.guide/blog/contest/2016/05/16/ricoh-cloud-api-with-iot-dev-contest.html
By following the guide, I think you can login successfully.

**Comment by codetricity** [comment]
I can login now. I believe that the problem @jjakshay has is with using Firefox on Linux. If you use Chrome 49 or newer, it should work.  I also had problems with Windows 10 default firewall settings. By disabling Windows firewall, I was able to get the connection working between two computers on the same subnet. Going from Windows 10 to Linux Ubuntu 16.04 worked with the default Ubuntu settings.

It's quite a cool application and I encourage everyone to give it a try.

My colleague @jcasman has this awesome app working with two MacBook Air computers, one running MacOS and one running Linux.

If you have a problem with login, feel free to write a note in comments section of the guide and we'll try and help. I have not tried to get it running on two different networks (like between San Francisco and Palo Alto), but would like to try at some point.
