### ISSUE TITLE
Broadcast sample doesn't work on npm install

### ISSUE THREAD

**Issue by Apolotary** [ricohapi/video-streaming-sample-app#6]
Hi,

I tried building the broadcast sample for Raspberry Pi 2 running the latest version of NOOBS image, followed the instructions in Readme and got this error:

`
npm WARN package.json ricohapi-video-streaming-sample@2.0.0 No README data
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! Error: version not found: ricohapi-auth@1.1.1
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.34-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/ricoh/video-streaming-sample-app/samples
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/ricoh/video-streaming-sample-app/samples/npm-debug.log
npm ERR! not ok code 0
`

Any clues on what could it be? It looks like the ricoh api is missing

Thanks!

**Comment by aikw** [comment]
Sorry, this repository is a sample of RICOH THETA x IoT Developers Contest 2016.
It is currently invalid because API was changed.
Here is a new one, so please look at here.
https://api.ricoh/

**Comment by Apolotary** [comment]
Got it, thanks!
